### PR TITLE
Restructure project per machine (and now to development branch)

### PR DESCRIPTION
**Pull request by Lucas-vdr-Horst**
The project is now restructured so the code is grouped per machine it'll run on.
setup.py is changed to give the option to install the dependencies of a specific machine, and the readme changed with these new installation instructions.

This change will most defiantly introduce merge conflict in branches which features are not yet complete.

### CODE REVIEW

**Comment by Lucas-vdr-Horst** [comment]
I think the conflict resolve went successful but not entirely sure, @Rubenvdbrink could you check the react code if it still works/is in order?

**Comment by RichardDev01** [comment]
> 

looked like it, i don;t see errors

**Review by RichardDev01 — APPROVED** [review]
I thought that it was alot of changed code but it was just renamed files, LGTM!

**Comment by Rubenvdbrink** [comment]
> I think the conflict resolve went successful but not entirely sure, @Rubenvdbrink could you check the react code if it still works/is in order?

Still works 👍

**Review by Rubenvdbrink — APPROVED** [review]
good work

**Pull request merged**
