### PR TITLE
Feature/69 path finding

### PR DESCRIPTION
**Pull request by Lucas-vdr-Horst**
The original User Story was only about the roomba algorithm, the path finding script kind of falls under that.

### CODE REVIEW

**Comment by Rubenvdbrink** [comment]
nice

**Review by Rubenvdbrink — APPROVED** [review]

**Review by RichardDev01 — COMMENTED** [review]
Is the imposter_robotmaster needed? I thought you said that is was temporary @Lucas-vdr-Horst

**Review by Max2411 — COMMENTED** [review]
Should all the requirements not be in the setup instead of a seperate reuquirements.txt file?

**Comment by Lucas-vdr-Horst** [comment]
Documented all functions, classes and modules as to comply with flake8.
Also removed "imposter_robomaster" as it couldn't fulfill it's original purpose, like Richard suggested.

**Comment by Lucas-vdr-Horst** [comment]
The commit's became quiet a mess since I had accidentally merged work from other unfinished feature branches in this branch. I've reverted these so that the net file changes are only about this feature,
but that's the explanation of the long and messy commit history.

**Comment by Lucas-vdr-Horst** [comment]
This has also been documented in the wiki.
That can be found here: [Path finding using RRT*](https://github.com/HU-ICT-LAB/RobotWars/wiki/Path-finding-using-RRT*)

**Review by RichardDev01 — APPROVED** [review]
LGTM, It is a lot of code but is clean and good to read

**Pull request merged**
